### ISSUE TITLE
Question: Is possible to use this to read the IR code generate by the app?

### ISSUE THREAD

**Issue by facutopa** [microneer/BroadlinkRMCodeFinder#1]
Hi @microneer maybe this question is silly but I need to know because I have a remote that the button turn on/off doesn't work. So, is possible to read the turn ON IR code generate by the app? (turn on button obtained by base data of Broadlink)
I don't know if I explained correctly. 

Thanks and cheers

**Comment by microneer** [comment]
If I understand correctly, you want to read out the turn ON code which is stored in the Broadlink official app or in the Broadlink hardware?

Then the answer is - 1) this software won't do that and 2) I'm not sure if it could be done.

Sorry about that.
